/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermTermIdRouteImport } from './routes/term.$termId'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermTermIdRoute = TermTermIdRouteImport.update({
  id: '/term/$termId',
  path: '/term/$termId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/term/$termId': typeof TermTermIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/term/$termId': typeof TermTermIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/term/$termId': typeof TermTermIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/status' | '/term/$termId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/status' | '/term/$termId'
  id: '__root__' | '/' | '/status' | '/term/$termId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  TermTermIdRoute: typeof TermTermIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/term/$termId': {
      id: '/term/$termId'
      path: '/term/$termId'
      fullPath: '/term/$termId'
      preLoaderRoute: typeof TermTermIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  TermTermIdRoute: TermTermIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
