export type { CompletenessConfig, CompletenessField } from '@/config/completeness'
export type * from '@/types'
export { COMPLETENESS_CONFIG, checkField, fieldExists } from '@/config/completeness'
export { LOCALES as locales } from '@/data/locales'
export { SOURCES as sources } from '@/data/sources'
export { TAGS as tags } from '@/data/tags'
export { TERMS as terms } from '@/data/terms'
export { TYPES as types } from '@/data/types'
